# Generated by Django 3.2.15 on 2023-09-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20230910_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedata',
            name='lat',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='geocodedata',
            name='lon',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
    ]
