# Generated by Django 3.2.15 on 2023-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('В пути', 'В пути'), ('Готовится', 'Готовится'), ('Принят', 'Принят'), ('Необработанный', 'Необработанный')], db_index=True, default='Необработанный', max_length=30, verbose_name='статус'),
        ),
    ]
