# Generated by Django 3.2.15 on 2023-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230910_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Электронные', 'Электронные'), ('Наличные', 'Наличные'), ('Не указан', 'Не указан')], db_index=True, default='Не указан', max_length=30, verbose_name='способ оплаты'),
        ),
    ]
