# Generated by Django 3.2.15 on 2023-09-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230910_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='orderelements',
            old_name='product_number',
            new_name='quantity',
        ),
    ]
