# Generated by Django 3.2.15 on 2023-09-10 14:12

import django.core.validators
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230910_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[foodcartapp.models.validate_price, django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
