# Generated by Django 3.2.15 on 2023-09-16 13:51

import django.core.validators
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelements',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[foodcartapp.models.validate_price, django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
